name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: yarn install
      
    - name: Type check
      run: yarn tsc
      
    - name: Lint
      run: yarn lint
      
    - name: Build
      run: yarn build 